import React, { useState, useEffect } from 'react'
import { supabase } from '../supabase'
import { useApp } from '../contexts/AppContext'
import { Card, Badge, Btn, Spinner, EmptyState, useToast } from '../components/UI'
import { formatDate } from '../styles'