import React, { useState, useEffect, useRef } from 'react'
import { supabase } from '../supabase'
import { useApp } from '../contexts/AppContext'
import { useAuth } from '../contexts/AuthContext'
import { Card, Badge, Modal, FormField, Input, Select, Btn, Spinner, EmptyState, Tabs, useToast } from '../components/UI'
import { formatDate, ROLE_LABELS } from '../styles'